CREATE TABLE user_types (
	id INT NOT NULL AUTO_INCREMENT,
	type VARCHAR(255) UNIQUE NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(id),
	INDEX(created_at)
);

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	type_id INT NOT NULL,
	username VARCHAR(255) UNIQUE NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(id),
	INDEX(username),
	INDEX(created_at),
	FOREIGN KEY(type_id) REFERENCES user_types(id)
);

INSERT INTO user_types (type)
VALUES
	('admin'),
	('user');
